/*
 * grunt-makeTextFiles
 * 
 *
 * Copyright (c) 2014 Incuna Ltd.
 * Licensed under the MIT license.
 */

'use strict';

module.exports = function(grunt) {

    // Please see the Grunt documentation for more information regarding task
    // creation: http://gruntjs.com/creating-tasks

    grunt.registerTask('makeTextFiles', 'Builds textfiles.js needed by eDetails', function() {
        // Nodejs libs.
        var fs = require('fs');
        var path = require('path');
        var requirejs = require('requirejs');
        var _ = require('lodash');

        //converts path relative to project root to absolute file system path 
        function projectToAbsPath(relPath) {
            return path.resolve(relPath);
        }
        //converts path relative to plugin root to absolute file system path 
        function pluginToAbsPath(relPath) {
            return path.join(__dirname, relPath);
        }

        // Merge task-specific and/or target-specific options with these defaults.
        var options = this.options({
            dataDirs: [],
            projectPath: 'project/',
            fileTypes: [
                'json',
                'yaml',
                'html'
            ]
        });

        //template file relative to this file
        var templateFileName = '../templates/textFiles.template.js';
        //project file paths
        var requireConfigPath = options.projectPath + 'jam/require.config.js';
        var destinationFileName = options.projectPath + 'textFiles.js';

        // Get requireJS config to be able to resolve module paths.
        if (grunt.file.exists(requireConfigPath)) {
            //use the require config generated by jam
            requirejs(projectToAbsPath(requireConfigPath));
        } else {
            //this is an old non-jam project?
            requirejs.config({
                'paths': {
                    'lib': '../lib',
                    'lodash': '../lib/require-underscore/underscore'
                }
            });
        }

        //Find the text files in all requireJS modules
        var root_len = requirejs.toUrl('').replace(/.js$/, '').length;
        //returns the relative module path to the requireJS root path
        function modulePath(module) {
            var modulePath = requirejs.toUrl(module).replace(/.js$/, '').substr(root_len);
            return modulePath;
        };

        var fileMatchString = '**/*.{' + options.fileTypes.join(',') + '}';
        var filePaths = _.chain(options.dataDirs).map(function (module) {
            // Use require to determine the actual file path of the module
            var processedDir = modulePath(module);
            var globOptions = {
                cwd: options.projectPath + processedDir
            }
            //get the files relative to each of the module directories
            var files = grunt.file.expand(globOptions, fileMatchString);

            // Add the module path back to the start of the relative file paths
            var projectFiles = _.map(files, function (file) {
                var moduleFile = path.join(module, file);
                return moduleFile;
            });
            return projectFiles;
        }).flatten().value();

        if (!filePaths) {
            //warn and exit grunt with a task
            grunt.warn('No files found', 0);
        }

        var sortedPaths = filePaths.sort();
        var textPaths = _(sortedPaths).map(function (filePath) {
            return 'text!' + filePath
        });

        // Write out the textFiles manifest using the template and the built files array
        //get absolute template path in filesystem
        var templatePath = pluginToAbsPath(templateFileName);
        //get template file contents
        var templateString = fs.readFileSync(templatePath, 'utf8');

        grunt.log.writeln('Writing ' + destinationFileName);
        var fileTemplate = _.template(templateString);
        var destinationFileContents = fileTemplate({
            textFiles: sortedPaths.join("',\n        '"),
            paths: textPaths.join("',\n    '")
        });
        // grunt.log.writeln('destinationFileContents ' + destinationFileContents);
        var destinationPath = projectToAbsPath(destinationFileName);
        fs.writeFileSync(destinationPath, destinationFileContents);
    });
};
